on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Code Analyzer
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: felixfaisal/attack-on-web
          path: attack-on-web
      - name: Code-Analyzer
        uses: felixfaisal/attack-on-web-actions@v1.2
        id: hello
      # Use the output from the `hello` step
