name: Attack on web 

on:
  push:
    branches: [ Reader ]
  pull_request:
    branches: [ Reader ]

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Installing dependencies 
      run: npm install 
    - name: Testing the software
      run: npm test 
    
    
